export type JobTemplate = {
  key: string;
  label_en: string;
  label_ar: string;
  data: {
    title_en: string; title_ar: string;
    department_en: string; department_ar: string;
    location_en: string; location_ar: string;
    description_en: string; description_ar: string;
    responsibilities_en: string; responsibilities_ar: string;
    requirements_en: string; requirements_ar: string;
    nice_to_have_en: string; nice_to_have_ar: string;
    benefits_en: string; benefits_ar: string;
    employment_type: "full_time" | "part_time" | "contract" | "internship";
    experience_level: "intern" | "junior" | "mid" | "senior" | "lead";
    remote_policy: "onsite" | "hybrid" | "remote";
    min_years_experience: number;
    skills: string[];
  };
};

const STANDARD_BENEFITS_EN = "- Competitive salary and annual bonus\n- Medical insurance for you and your family\n- Paid annual leave and public holidays\n- Continuous training and certifications\n- Modern tools and a collaborative environment";
const STANDARD_BENEFITS_AR = "- راتب تنافسي ومكافأة سنوية\n- تأمين طبي لك ولعائلتك\n- إجازة سنوية مدفوعة وعطلات رسمية\n- تدريب مستمر وشهادات احترافية\n- أدوات حديثة وبيئة عمل تعاونية";

export const JOB_TEMPLATES: JobTemplate[] = [
  {
    key: "security_engineer",
    label_en: "Security Systems Engineer (CCTV / Access Control)",
    label_ar: "مهندس أنظمة أمنية (كاميرات مراقبة / تحكم في الوصول)",
    data: {
      title_en: "Security Systems Engineer",
      title_ar: "مهندس أنظمة أمنية",
      department_en: "Security & Low Current",
      department_ar: "الأمن والتيار الخفيف",
      location_en: "Cairo, Egypt",
      location_ar: "القاهرة، مصر",
      description_en: "Design, install and commission enterprise security systems including CCTV, access control, intrusion detection and intercom across commercial and government projects.",
      description_ar: "تصميم وتركيب وتشغيل أنظمة الأمن المتكاملة من كاميرات مراقبة وتحكم في الوصول وأنظمة الإنذار والاتصال الداخلي في المشاريع التجارية والحكومية.",
      responsibilities_en: "- Prepare technical designs, BoQs and shop drawings\n- Configure IP cameras, NVRs, access controllers and intercoms\n- Lead on-site installation, testing and commissioning\n- Train clients and produce as-built documentation\n- Coordinate with consultants and project managers",
      responsibilities_ar: "- إعداد التصاميم الفنية وجداول الكميات والمخططات التنفيذية\n- إعداد كاميرات IP وأجهزة NVR وأنظمة التحكم في الوصول والاتصال الداخلي\n- قيادة التركيب والاختبار والتشغيل في الموقع\n- تدريب العملاء وإعداد الوثائق النهائية\n- التنسيق مع الاستشاريين ومديري المشاريع",
      requirements_en: "- Bachelor's degree in Electrical / Electronics / Communications\n- 3+ years hands-on with Hikvision, Axis, HID or LenelS2\n- Strong networking fundamentals (VLAN, PoE, IP addressing)\n- Ability to read architectural and MEP drawings\n- Excellent written and spoken English",
      requirements_ar: "- بكالوريوس في الهندسة الكهربائية أو الإلكترونيات أو الاتصالات\n- خبرة لا تقل عن 3 سنوات في Hikvision أو Axis أو HID أو LenelS2\n- إلمام قوي بأساسيات الشبكات (VLAN, PoE, IP)\n- القدرة على قراءة المخططات المعمارية والميكانيكية\n- إجادة اللغة الإنجليزية تحدثاً وكتابة",
      nice_to_have_en: "- Certifications: CCTV, Lenel, Genetec\n- Experience with Milestone XProtect\n- Egyptian driving license",
      nice_to_have_ar: "- شهادات: CCTV، Lenel، Genetec\n- خبرة في Milestone XProtect\n- رخصة قيادة سعودية",
      benefits_en: STANDARD_BENEFITS_EN,
      benefits_ar: STANDARD_BENEFITS_AR,
      employment_type: "full_time", experience_level: "mid", remote_policy: "onsite",
      min_years_experience: 3,
      skills: ["CCTV","Access Control","IP Networking","Hikvision","Genetec"],
    },
  },
  {
    key: "network_engineer",
    label_en: "Network Engineer (ICT Infrastructure)",
    label_ar: "مهندس شبكات (بنية تحتية لتقنية المعلومات)",
    data: {
      title_en: "Network Engineer",
      title_ar: "مهندس شبكات",
      department_en: "ICT Infrastructure",
      department_ar: "البنية التحتية لتقنية المعلومات",
      location_en: "Hybrid",
      location_ar: "هجين",
      description_en: "Design and operate enterprise LAN/WAN, wireless and security infrastructure for mission-critical clients.",
      description_ar: "تصميم وتشغيل شبكات LAN/WAN والشبكات اللاسلكية وأنظمة الأمن للعملاء ذوي الأنظمة الحرجة.",
      responsibilities_en: "- Design and deploy Cisco / Aruba / Fortinet stacks\n- Implement routing, switching, firewalls and VPN\n- Monitor performance and resolve incidents within SLA\n- Document architecture and run-books\n- Mentor junior engineers",
      responsibilities_ar: "- تصميم ونشر حلول Cisco / Aruba / Fortinet\n- تنفيذ التوجيه والتبديل وجدران الحماية وشبكات VPN\n- متابعة الأداء وحل الحوادث ضمن اتفاقيات الخدمة\n- توثيق البنية التحتية وكتيبات التشغيل\n- توجيه المهندسين الجدد",
      requirements_en: "- Bachelor's degree in Computer / Network Engineering\n- 4+ years enterprise networking experience\n- CCNP or equivalent certification\n- Strong troubleshooting under pressure",
      requirements_ar: "- بكالوريوس في هندسة الحاسب أو الشبكات\n- خبرة لا تقل عن 4 سنوات في الشبكات المؤسسية\n- شهادة CCNP أو ما يعادلها\n- مهارات قوية في تحليل الأعطال تحت الضغط",
      nice_to_have_en: "- CCIE / Fortinet NSE\n- SD-WAN experience\n- Cloud networking (AWS / Azure)",
      nice_to_have_ar: "- شهادات CCIE / Fortinet NSE\n- خبرة في SD-WAN\n- شبكات سحابية (AWS / Azure)",
      benefits_en: STANDARD_BENEFITS_EN, benefits_ar: STANDARD_BENEFITS_AR,
      employment_type: "full_time", experience_level: "senior", remote_policy: "hybrid",
      min_years_experience: 4,
      skills: ["Cisco","Fortinet","Routing","Switching","VPN"],
    },
  },
  {
    key: "av_engineer",
    label_en: "AV Solutions Engineer (Audio Visual)",
    label_ar: "مهندس حلول الصوتيات والمرئيات",
    data: {
      title_en: "AV Solutions Engineer",
      title_ar: "مهندس حلول الصوتيات والمرئيات",
      department_en: "Audio Visual",
      department_ar: "الصوتيات والمرئيات",
      location_en: "Cairo",
      location_ar: "القاهرة",
      description_en: "Deliver end-to-end AV solutions for boardrooms, auditoriums and command centers — from design to commissioning.",
      description_ar: "تنفيذ حلول صوتيات ومرئيات متكاملة لقاعات الاجتماعات والمسارح ومراكز التحكم من التصميم حتى التشغيل.",
      responsibilities_en: "- Design AV systems (Crestron, Extron, QSC, Shure)\n- Program control systems and DSP\n- Lead installation and on-site commissioning\n- Handover and end-user training",
      responsibilities_ar: "- تصميم أنظمة AV (Crestron, Extron, QSC, Shure)\n- برمجة أنظمة التحكم وأجهزة DSP\n- قيادة التركيب والتشغيل في الموقع\n- التسليم وتدريب المستخدمين",
      requirements_en: "- 3+ years professional AV experience\n- CTS certification preferred\n- Ability to read AV schematics and rack drawings",
      requirements_ar: "- خبرة لا تقل عن 3 سنوات في حلول AV الاحترافية\n- شهادة CTS مفضلة\n- القدرة على قراءة مخططات AV ورسومات الرفوف",
      nice_to_have_en: "- CTS-D / CTS-I\n- Crestron / Q-SYS programming",
      nice_to_have_ar: "- شهادات CTS-D / CTS-I\n- برمجة Crestron / Q-SYS",
      benefits_en: STANDARD_BENEFITS_EN, benefits_ar: STANDARD_BENEFITS_AR,
      employment_type: "full_time", experience_level: "mid", remote_policy: "onsite",
      min_years_experience: 3,
      skills: ["Crestron","Extron","QSC","DSP"],
    },
  },
  {
    key: "project_manager",
    label_en: "Project Manager (Systems Integration)",
    label_ar: "مدير مشاريع (تكامل الأنظمة)",
    data: {
      title_en: "Project Manager",
      title_ar: "مدير مشاريع",
      department_en: "Project Management Office",
      department_ar: "مكتب إدارة المشاريع",
      location_en: "Cairo",
      location_ar: "القاهرة",
      description_en: "Plan and deliver multi-disciplinary integration projects covering security, ICT, AV and data center scopes.",
      description_ar: "تخطيط وتسليم مشاريع تكامل متعددة التخصصات تشمل الأمن وتقنية المعلومات والصوتيات والمرئيات ومراكز البيانات.",
      responsibilities_en: "- Own scope, schedule, cost and quality\n- Manage stakeholders, vendors and subcontractors\n- Maintain RAID logs and progress reports\n- Run weekly steering meetings",
      responsibilities_ar: "- إدارة النطاق والجدول والتكلفة والجودة\n- إدارة أصحاب المصلحة والموردين والمقاولين من الباطن\n- متابعة سجلات RAID وتقارير التقدم\n- إدارة اجتماعات التوجيه الأسبوعية",
      requirements_en: "- Bachelor's degree in Engineering or related field\n- 5+ years delivering integration / construction projects\n- PMP or PRINCE2 certified\n- Strong client-facing communication",
      requirements_ar: "- بكالوريوس في الهندسة أو مجال ذي صلة\n- خبرة لا تقل عن 5 سنوات في مشاريع التكامل أو الإنشاءات\n- شهادة PMP أو PRINCE2\n- مهارات تواصل قوية مع العملاء",
      nice_to_have_en: "- Experience with Primavera P6\n- Bilingual Arabic/English",
      nice_to_have_ar: "- خبرة في Primavera P6\n- إجادة العربية والإنجليزية",
      benefits_en: STANDARD_BENEFITS_EN, benefits_ar: STANDARD_BENEFITS_AR,
      employment_type: "full_time", experience_level: "senior", remote_policy: "onsite",
      min_years_experience: 5,
      skills: ["PMP","Stakeholder Management","Scheduling","Risk"],
    },
  },
  {
    key: "sales_engineer",
    label_en: "Pre-Sales / Sales Engineer",
    label_ar: "مهندس مبيعات / ما قبل البيع",
    data: {
      title_en: "Pre-Sales Engineer",
      title_ar: "مهندس ما قبل البيع",
      department_en: "Sales",
      department_ar: "المبيعات",
      location_en: "Cairo",
      location_ar: "القاهرة",
      description_en: "Translate client needs into winning technical proposals across security, ICT, AV and data center solutions.",
      description_ar: "ترجمة احتياجات العملاء إلى عروض فنية فائزة في مجالات الأمن وتقنية المعلومات والصوتيات والمرئيات ومراكز البيانات.",
      responsibilities_en: "- Lead solution design and BoQ preparation\n- Present to clients and consultants\n- Coordinate with vendors for pricing and approvals\n- Support tender submissions",
      responsibilities_ar: "- قيادة تصميم الحلول وإعداد جداول الكميات\n- تقديم العروض للعملاء والاستشاريين\n- التنسيق مع الموردين للأسعار والاعتمادات\n- دعم تقديم العطاءات",
      requirements_en: "- 3+ years in pre-sales for low-current or ICT integration\n- Strong technical writing\n- Excellent English and Arabic",
      requirements_ar: "- خبرة لا تقل عن 3 سنوات في ما قبل البيع للتيار الخفيف أو تقنية المعلومات\n- مهارات كتابة فنية قوية\n- إجادة الإنجليزية والعربية",
      nice_to_have_en: "- Vendor accreditations (Cisco, HPE, Hikvision)",
      nice_to_have_ar: "- اعتمادات الموردين (Cisco, HPE, Hikvision)",
      benefits_en: STANDARD_BENEFITS_EN, benefits_ar: STANDARD_BENEFITS_AR,
      employment_type: "full_time", experience_level: "mid", remote_policy: "hybrid",
      min_years_experience: 3,
      skills: ["Pre-Sales","Solution Design","BoQ","Tenders"],
    },
  },
  {
    key: "software_engineer",
    label_en: "Full-Stack Software Engineer",
    label_ar: "مهندس برمجيات متكامل",
    data: {
      title_en: "Full-Stack Software Engineer",
      title_ar: "مهندس برمجيات متكامل",
      department_en: "Software Engineering",
      department_ar: "هندسة البرمجيات",
      location_en: "Remote",
      location_ar: "عن بُعد",
      description_en: "Build and maintain modern web platforms with React, TypeScript and a serverless backend.",
      description_ar: "بناء وصيانة منصات ويب حديثة باستخدام React وTypeScript وخلفية بدون خوادم.",
      responsibilities_en: "- Ship features end-to-end (UI, API, database)\n- Write tested, accessible, performant code\n- Review pull requests and mentor peers\n- Participate in product discovery",
      responsibilities_ar: "- تنفيذ الميزات من البداية للنهاية (الواجهة، واجهة برمجة التطبيقات، قاعدة البيانات)\n- كتابة كود مختبر يمكن الوصول إليه وعالي الأداء\n- مراجعة طلبات الدمج وتوجيه الزملاء\n- المشاركة في اكتشاف المنتج",
      requirements_en: "- 3+ years with React + TypeScript\n- Experience with Postgres and REST/GraphQL\n- Solid understanding of testing and CI/CD",
      requirements_ar: "- خبرة لا تقل عن 3 سنوات في React + TypeScript\n- خبرة في Postgres وREST/GraphQL\n- فهم قوي للاختبار وCI/CD",
      nice_to_have_en: "- Open source contributions\n- Tailwind, TanStack Router, Supabase",
      nice_to_have_ar: "- مساهمات في المصادر المفتوحة\n- Tailwind, TanStack Router, Supabase",
      benefits_en: STANDARD_BENEFITS_EN, benefits_ar: STANDARD_BENEFITS_AR,
      employment_type: "full_time", experience_level: "mid", remote_policy: "remote",
      min_years_experience: 3,
      skills: ["React","TypeScript","Postgres","Node.js"],
    },
  },
  {
    key: "data_center_engineer",
    label_en: "Data Center Engineer",
    label_ar: "مهندس مراكز بيانات",
    data: {
      title_en: "Data Center Engineer",
      title_ar: "مهندس مراكز بيانات",
      department_en: "Data Center",
      department_ar: "مراكز البيانات",
      location_en: "Cairo",
      location_ar: "القاهرة",
      description_en: "Design and operate Tier III/IV data center facilities including power, cooling, fire suppression and structured cabling.",
      description_ar: "تصميم وتشغيل مراكز بيانات من المستوى الثالث والرابع، تشمل الطاقة والتبريد وإطفاء الحرائق والكابلات المنظمة.",
      responsibilities_en: "- Maintain UPS, PDU, CRAC and BMS systems\n- Manage capacity, cabling and rack layouts\n- Coordinate planned maintenance windows\n- Ensure uptime SLA compliance",
      responsibilities_ar: "- صيانة أنظمة UPS وPDU وCRAC وBMS\n- إدارة السعات والكابلات وتخطيط الرفوف\n- تنسيق نوافذ الصيانة المخططة\n- ضمان الامتثال لاتفاقيات وقت التشغيل",
      requirements_en: "- 4+ years in data center operations\n- Knowledge of TIA-942 and Uptime Institute standards\n- Hands-on with structured cabling (Cat6A, fiber)",
      requirements_ar: "- خبرة لا تقل عن 4 سنوات في عمليات مراكز البيانات\n- معرفة بمعايير TIA-942 ومعهد Uptime\n- خبرة عملية في الكابلات المنظمة (Cat6A، الألياف)",
      nice_to_have_en: "- CDCP / CDCS certification\n- DCIM tools experience",
      nice_to_have_ar: "- شهادات CDCP / CDCS\n- خبرة في أدوات DCIM",
      benefits_en: STANDARD_BENEFITS_EN, benefits_ar: STANDARD_BENEFITS_AR,
      employment_type: "full_time", experience_level: "senior", remote_policy: "onsite",
      min_years_experience: 4,
      skills: ["UPS","Cooling","Structured Cabling","BMS"],
    },
  },
  {
    key: "hr_specialist",
    label_en: "HR Specialist",
    label_ar: "أخصائي موارد بشرية",
    data: {
      title_en: "HR Specialist",
      title_ar: "أخصائي موارد بشرية",
      department_en: "Human Resources",
      department_ar: "الموارد البشرية",
      location_en: "Cairo",
      location_ar: "القاهرة",
      description_en: "Own recruitment, onboarding and employee experience across engineering and corporate teams.",
      description_ar: "إدارة التوظيف والإلحاق وتجربة الموظف عبر الفرق الهندسية والإدارية.",
      responsibilities_en: "- Manage end-to-end recruitment\n- Run onboarding and orientation\n- Maintain HRIS and compliance records\n- Support employee engagement initiatives",
      responsibilities_ar: "- إدارة دورة التوظيف الكاملة\n- إجراء برامج الإلحاق والتعريف\n- صيانة نظام HRIS وسجلات الامتثال\n- دعم مبادرات إشراك الموظفين",
      requirements_en: "- Bachelor's degree in HR / Business\n- 2+ years HR generalist experience\n- Familiar with Egyptian labor law\n- Strong communication in Arabic and English",
      requirements_ar: "- بكالوريوس في الموارد البشرية أو إدارة الأعمال\n- خبرة لا تقل عن سنتين كأخصائي موارد بشرية\n- إلمام بنظام العمل السعودي\n- مهارات تواصل قوية بالعربية والإنجليزية",
      nice_to_have_en: "- SHRM-CP / aPHR\n- Experience with Bayzat or Workday",
      nice_to_have_ar: "- شهادات SHRM-CP / aPHR\n- خبرة في Bayzat أو Workday",
      benefits_en: STANDARD_BENEFITS_EN, benefits_ar: STANDARD_BENEFITS_AR,
      employment_type: "full_time", experience_level: "mid", remote_policy: "onsite",
      min_years_experience: 2,
      skills: ["Recruitment","Onboarding","HRIS","Labor Law"],
    },
  },
  {
    key: "accountant",
    label_en: "Accountant",
    label_ar: "محاسب",
    data: {
      title_en: "Accountant",
      title_ar: "محاسب",
      department_en: "Finance",
      department_ar: "المالية",
      location_en: "Cairo",
      location_ar: "القاهرة",
      description_en: "Maintain accurate books, manage AP/AR cycles and support monthly close and VAT reporting.",
      description_ar: "حفظ سجلات محاسبية دقيقة وإدارة دورات الذمم الدائنة والمدينة ودعم الإقفال الشهري وتقارير ضريبة القيمة المضافة.",
      responsibilities_en: "- Post journals and reconcile bank accounts\n- Manage invoices, payments and collections\n- Prepare VAT and WHT filings\n- Support monthly and yearly close",
      responsibilities_ar: "- ترحيل القيود وتسوية الحسابات البنكية\n- إدارة الفواتير والمدفوعات والتحصيل\n- إعداد إقرارات ضريبة القيمة المضافة والاستقطاع\n- دعم الإقفال الشهري والسنوي",
      requirements_en: "- Bachelor's degree in Accounting or Finance\n- 2+ years in a similar role\n- Proficient with ERP (SAP, Oracle, Odoo)\n- Strong Excel skills",
      requirements_ar: "- بكالوريوس في المحاسبة أو المالية\n- خبرة لا تقل عن سنتين في دور مماثل\n- إتقان أنظمة ERP (SAP, Oracle, Odoo)\n- مهارات Excel قوية",
      nice_to_have_en: "- SOCPA / CMA candidate\n- IFRS exposure",
      nice_to_have_ar: "- متقدم لشهادة SOCPA أو CMA\n- خبرة في معايير IFRS",
      benefits_en: STANDARD_BENEFITS_EN, benefits_ar: STANDARD_BENEFITS_AR,
      employment_type: "full_time", experience_level: "mid", remote_policy: "onsite",
      min_years_experience: 2,
      skills: ["Accounting","ERP","VAT","Excel"],
    },
  },
  {
    key: "marketing_specialist",
    label_en: "Digital Marketing Specialist",
    label_ar: "أخصائي تسويق رقمي",
    data: {
      title_en: "Digital Marketing Specialist",
      title_ar: "أخصائي تسويق رقمي",
      department_en: "Marketing",
      department_ar: "التسويق",
      location_en: "Hybrid",
      location_ar: "هجين",
      description_en: "Plan and execute B2B campaigns across SEO, paid media, content and LinkedIn to drive qualified pipeline.",
      description_ar: "تخطيط وتنفيذ حملات B2B عبر تحسين محركات البحث والإعلانات المدفوعة والمحتوى وLinkedIn لجذب فرص مؤهلة.",
      responsibilities_en: "- Run SEO, SEM and LinkedIn campaigns\n- Produce bilingual content (EN/AR)\n- Track KPIs via GA4 and HubSpot\n- Coordinate with sales on MQL hand-off",
      responsibilities_ar: "- تشغيل حملات SEO وSEM وLinkedIn\n- إنتاج محتوى ثنائي اللغة (إنجليزي/عربي)\n- متابعة المؤشرات عبر GA4 وHubSpot\n- التنسيق مع المبيعات لتسليم العملاء المؤهلين",
      requirements_en: "- 3+ years in B2B digital marketing\n- Hands-on with Google Ads, GA4, LinkedIn Ads\n- Strong bilingual copywriting",
      requirements_ar: "- خبرة لا تقل عن 3 سنوات في التسويق الرقمي B2B\n- خبرة عملية في Google Ads وGA4 وLinkedIn Ads\n- كتابة إعلانية قوية بالعربية والإنجليزية",
      nice_to_have_en: "- HubSpot certified\n- ABM experience",
      nice_to_have_ar: "- شهادة HubSpot\n- خبرة في ABM",
      benefits_en: STANDARD_BENEFITS_EN, benefits_ar: STANDARD_BENEFITS_AR,
      employment_type: "full_time", experience_level: "mid", remote_policy: "hybrid",
      min_years_experience: 3,
      skills: ["SEO","Google Ads","LinkedIn","Copywriting"],
    },
  },
  {
    key: "customer_support",
    label_en: "Customer Support Engineer",
    label_ar: "مهندس دعم عملاء",
    data: {
      title_en: "Customer Support Engineer",
      title_ar: "مهندس دعم عملاء",
      department_en: "Customer Success",
      department_ar: "نجاح العملاء",
      location_en: "Cairo",
      location_ar: "القاهرة",
      description_en: "Provide L1/L2 support for installed systems, resolve tickets within SLA and improve documentation.",
      description_ar: "تقديم دعم L1/L2 للأنظمة المثبتة وحل التذاكر ضمن اتفاقيات الخدمة وتحسين التوثيق.",
      responsibilities_en: "- Triage and resolve tickets\n- Run remote diagnostics and dispatch field teams\n- Maintain knowledge base articles\n- Report on SLA and CSAT",
      responsibilities_ar: "- تصنيف وحل التذاكر\n- إجراء التشخيص عن بُعد وإرسال الفرق الميدانية\n- صيانة مقالات قاعدة المعرفة\n- إعداد تقارير SLA وCSAT",
      requirements_en: "- 2+ years in technical customer support\n- Networking and Windows Server basics\n- Excellent communication in Arabic and English",
      requirements_ar: "- خبرة لا تقل عن سنتين في الدعم الفني للعملاء\n- أساسيات الشبكات وWindows Server\n- تواصل ممتاز بالعربية والإنجليزية",
      nice_to_have_en: "- ITIL Foundation\n- Experience with ticketing platforms (Zendesk, Freshdesk)",
      nice_to_have_ar: "- شهادة ITIL Foundation\n- خبرة في منصات التذاكر (Zendesk, Freshdesk)",
      benefits_en: STANDARD_BENEFITS_EN, benefits_ar: STANDARD_BENEFITS_AR,
      employment_type: "full_time", experience_level: "junior", remote_policy: "onsite",
      min_years_experience: 2,
      skills: ["Support","ITIL","Networking","Windows Server"],
    },
  },
  {
    key: "internship",
    label_en: "Engineering Internship",
    label_ar: "تدريب هندسي",
    data: {
      title_en: "Engineering Internship",
      title_ar: "تدريب هندسي",
      department_en: "Engineering",
      department_ar: "الهندسة",
      location_en: "Cairo",
      location_ar: "القاهرة",
      description_en: "Hands-on internship across our engineering teams — shadow senior engineers and contribute to real projects.",
      description_ar: "تدريب عملي ضمن فرقنا الهندسية — العمل مع كبار المهندسين والمساهمة في مشاريع حقيقية.",
      responsibilities_en: "- Assist with site surveys and documentation\n- Shadow installation and commissioning teams\n- Complete a capstone project at the end of the program",
      responsibilities_ar: "- المساعدة في المسوحات الميدانية والتوثيق\n- مرافقة فرق التركيب والتشغيل\n- إنجاز مشروع تخرج في نهاية البرنامج",
      requirements_en: "- Final-year or recent graduate (Engineering / CS)\n- Eagerness to learn and good English\n- Available full-time for 3-6 months",
      requirements_ar: "- طالب سنة أخيرة أو خريج حديث (هندسة / علوم حاسب)\n- شغف للتعلم وإجادة الإنجليزية\n- متفرغ بدوام كامل لمدة 3-6 أشهر",
      nice_to_have_en: "- Personal projects or GitHub portfolio",
      nice_to_have_ar: "- مشاريع شخصية أو ملف GitHub",
      benefits_en: "- Monthly stipend\n- Mentorship from senior engineers\n- Certificate upon completion\n- Potential full-time offer",
      benefits_ar: "- مكافأة شهرية\n- إرشاد من كبار المهندسين\n- شهادة عند الإتمام\n- إمكانية التعيين بدوام كامل",
      employment_type: "internship", experience_level: "intern", remote_policy: "onsite",
      min_years_experience: 0,
      skills: ["Learning","Teamwork","Documentation"],
    },
  },
];