-- =================================================================
-- Ensure Projects Table Exists and Seed Default Projects
-- Run this in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/hdbzvoitzyvehyeqygmq/sql
-- =================================================================

CREATE TABLE IF NOT EXISTS public.projects (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  image text NOT NULL DEFAULT '',
  title_en text NOT NULL DEFAULT '',
  title_ar text NOT NULL DEFAULT '',
  industry text NOT NULL DEFAULT '',
  desc_en text NOT NULL DEFAULT '',
  desc_ar text NOT NULL DEFAULT '',
  active boolean NOT NULL DEFAULT true,
  meta_title_en text,
  meta_title_ar text,
  meta_description_en text,
  meta_description_ar text,
  meta_keywords text,
  og_image text,
  canonical_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Ensure active column exists if table was created previously
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS active boolean NOT NULL DEFAULT true;

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- 1. Public can read projects
DROP POLICY IF EXISTS "Projects publicly readable" ON public.projects;
CREATE POLICY "Projects publicly readable"
  ON public.projects FOR SELECT
  USING (true);

-- 2. Authenticated admins can manage projects
DROP POLICY IF EXISTS "Admins manage projects" ON public.projects;
CREATE POLICY "Admins manage projects"
  ON public.projects FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);

-- 3. Seed default Case Studies / Projects if table is empty
INSERT INTO public.projects (id, image, title_en, title_ar, industry, desc_en, desc_ar)
OVERRIDING SYSTEM VALUE
VALUES
  (
    1,
    'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
    'Tier-III Data Center for Regional Telecom Operator',
    'مركز بيانات Tier-III لمشغل اتصالات إقليمي',
    'Telecom',
    'Turnkey design, structured cabling, precision cooling and power redundancy across 2,400 sqm.',
    'تصميم متكامل، كابلات هيكلية، تبريد دقيق وأنظمة طاقة احتياطية على مساحة 2,400 متر مربع.'
  ),
  (
    2,
    'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800&q=80',
    'Integrated Perimeter Security for Government Campus',
    'أمن محيطي متكامل لمجمع حكومي',
    'Government',
    'Fiber-optic fence intrusion detection, radar-assisted PTZ tracking and central command room.',
    'أنظمة كشف التسلل بالألياف الضوئية، تتبع راداري بكاميرات متحركة وغرفة تحكم وسيطرة مركزية.'
  ),
  (
    3,
    'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&q=80',
    'Industrial IoT & Surveillance for Petrochemical Plant',
    'إنترنت الأشياء الصناعي والمراقبة لمصنع بتروكيماويات',
    'Oil & Gas',
    'ATEX-certified explosion-proof cameras, thermal gas leak detection and wireless mesh backhaul.',
    'كاميرات مقاومة للانفجار معتمدة من ATEX، كشف حراري لتسرب الغاز وشبكة لاسلكية متداخلة.'
  ),
  (
    4,
    'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    'Guest Network & Smart Room Automation for 5-Star Hotel',
    'شبكة ضيوف وأتمتة غرف ذكية لفندق 5 نجوم',
    'Hospitality',
    'High-density Wi-Fi 6 across 450 keys, IPTV, digital signage and guest room management system (GRMS).',
    'شبكة Wi-Fi 6 عالية الكثافة عبر 450 غرفة، IPTV، شاشات رقمية ونظام إدارة غرف النزلاء (GRMS).'
  ),
  (
    5,
    'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80',
    'Smart Factory Network & Access Control',
    'شبكة المصنع الذكي والتحكم في الدخول',
    'Manufacturing',
    'Industrial Ethernet, biometric turnstiles, automated vehicle barrier recognition and warehouse Wi-Fi.',
    'إيثرنت صناعي، بوابات دخول بيومترية، التعرف التلقائي على لوحات المركبات وتغطية واي فاي للمستودعات.'
  ),
  (
    6,
    'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
    'Smart City Mixed-Use Master Community',
    'مجتمع عمراني متعدد الاستخدامات للمدن الذكية',
    'Real Estate',
    'FTTH GPON network, centralized ANPR parking management, IP video intercom and smart lighting.',
    'شبكة ألياف ضوئية FTTH GPON، إدارة مواقف ذكية، اتصال داخلي بالفيديو وإضاءة ذكية.'
  )
ON CONFLICT (id) DO NOTHING;
